language: java

jdk:
  - oraclejdk7
  - oraclejdk8

# whitelist
branches:
  only:
    - master
    - "2.7"
    - "2.8"

arch:
  - ppc64le
  - amd64

before_install: 
        - mkdir -p /opt/maven
        - curl https://downloads.apache.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz|tar -xz --strip 1 -C /opt/maven
        - export MAVEN_HOME=/opt/maven
        - export PATH=${MAVEN_HOME}/bin:${PATH}
